name: frontend_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  socket_io_client: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/shop/
    - assets/images/tableroFuturista.png
    - assets/images/avatares/
  uses-material-design: true
